### ISSUE TITLE
Crash while using dockermachine provider with amazonec2 driver

### ISSUE THREAD

**Issue by ginjo** [giacomocariello/terraform-provider-dockermachine#1]
Hi, I'm running into a terraform crash when using the dockermachine provider in `terraform apply` and thought I'd post here to see if I'm missing something essential. If I could get this to work, it would perfectly suit my needs. Here's some more info (versions, .tf file, crash output). Any thoughts appreciated, thanks.

Mac OX 10.11.6

Terraform info `brew info terraform`

```
  terraform: stable 0.11.4 (bottled), HEAD
  Tool to build, change, and version infrastructure
  https://www.terraform.io/
  Conflicts with:
    tfenv (because tfenv symlinks terraform binaries)
  /usr/local/Cellar/terraform/0.11.3 (7 files, 79.9MB)
    Poured from bottle on 2018-03-15 at 18:57:35
  /usr/local/Cellar/terraform/0.11.4 (7 files, 80.2MB) *
    Poured from bottle on 2018-03-16 at 15:39:56
  From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform.rb
  ==> Dependencies
  Build: go ✔, gox ✘
  ==> Options
  --HEAD
  	Install HEAD version
  ==> Caveats
  zsh completions have been installed to:
    /usr/local/share/zsh/site-functions
```

Terraform version

```
  2018/03/16 15:42:04 [INFO] Terraform version: 0.11.4  
  2018/03/16 15:42:04 [INFO] Go runtime version: go1.10
  2018/03/16 15:42:04 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.11.4/bin/terraform", "version"}
  2018/03/16 15:42:04 [DEBUG] Attempting to open CLI config file: /Users/wbr/.terraformrc
  2018/03/16 15:42:04 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
  2018/03/16 15:42:04 [INFO] CLI command args: []string{"version"}
  Terraform v0.11.4
  2018/03/16 15:42:04 [WARN] found legacy provider "terraform-provider-dockermachine"
  + provider.aws v1.11.0
  + provider.dockermachine (unversioned)
```

Go version

```
  go version go1.10 darwin/amd64
```

AWS cli version (I'm using the ~/.aws/credentials file for aws authentication)

```
  aws-cli/1.11.170 Python/2.7.10 Darwin/15.6.0 botocore/1.7.28
```

dockermachine.tf

```
provider "dockermachine" {
  # Region is not a valid key in dockermachine provider
  #region = "us-west-2"
}

resource "dockermachine_amazonec2" "node" {
    count = 1
    name = "${format("node-%02d", count.index+1)}"

    # docker-machine-amaconec2 specific.
    engine_insecure_registry = [
      "localhost:5000",
      "registry:5000",
      "127.0.0.1:5000"
    ]
    amazonec2_ssh_user = "admin"
    amazonec2_region = "us-west-2"
    amazonec2_instance_type = "t2.nano"
    amazonec2_ami = "ami-221ea342"
    amazonec2_device_name = "/dev/xvda"
    amazonec2_root_size = 8
    amazonec2_volume_type = "gp2"
    amazonec2_security_group = ["docker-machine"]
    amazonec2_keypair_name = "docker-machine"
    
    
    provisioner "remote-exec" {
        inline = [
            "touch /tmp/this_is_a_test",
        ]
        connection {
            type        = "ssh"
            host        = "${self.ssh_hostname}"
            port        = "${self.ssh_port}"
            user        = "${self.ssh_username}"
            private_key = "${file("${self.ssh_keypath}")}"
        }
    }
}
```

Output from `terraform apply`

```
  registry:terraform wbr$ terraform apply
  2018/03/16 15:27:09 [INFO] Terraform version: 0.11.3  
  2018/03/16 15:27:09 [INFO] Go runtime version: go1.9.3
  2018/03/16 15:27:09 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.11.3/bin/terraform", "apply"}
  2018/03/16 15:27:09 [DEBUG] Attempting to open CLI config file: /Users/wbr/.terraformrc
  2018/03/16 15:27:09 [INFO] CLI command args: []string{"apply"}
  2018/03/16 15:27:09 [INFO] command: empty terraform config, returning nil
  2018/03/16 15:27:09 [INFO] command: backend initialized: <nil>
  2018/03/16 15:27:09 [WARN] found legacy provider "terraform-provider-dockermachine"
  2018/03/16 15:27:09 [INFO] command: backend <nil> is not enhanced, wrapping in local
  2018/03/16 15:27:09 [INFO] backend/local: starting Apply operation
  2018/03/16 15:27:09 [INFO] terraform: building graph: GraphTypeInput
  terraform.NodeApplyableProvider
  orm.graphNodeCloseProvisioner
  2018/03/16 15:27:09 [INFO] terraform: building graph: GraphTypeValidate
  rmachine_amazonec2.node - *terraform.NodeValidatableResource
  zonec2.node - *terraform.NodeValidatableResource
  root - terraform.graphNodeRoot
    meta.count-boundary (count boundary fixup) - *terraform.NodeCountBoundary
    provider.aws (close) - *terraform.graphNodeCloseProvider
    provider.dockermachine (close) - *terraform.graphNodeCloseProvider
    provisioner.file (close) - *terraform.graphNodeCloseProvisioner
    provisioner.remote-exec (close) - *terraform.graphNodeCloseProvisioner
  te-exec (close) - *terraform.graphNodeCloseProvisioner
  2018/03/16 15:27:09 [INFO] backend/local: apply calling Refresh
  2018/03/16 15:27:09 [INFO] terraform: building graph: GraphTypeRefresh
  aws_instance.example: Refreshing state... (ID: i-09ec1730b3b525d27)
  2018/03/16 15:27:13 [INFO] backend/local: apply calling Plan
  2018/03/16 15:27:13 [INFO] terraform: building graph: GraphTypePlan
  rmachine - *terraform.NodeApplyableProvider
  ) - *terraform.graphNodeCloseProvisioner

  An execution plan has been generated and is shown below.
  Resource actions are indicated with the following symbols:
    + create

  Terraform will perform the following actions:

    + dockermachine_amazonec2.node
        id:                               <computed>
        address:                          <computed>
        amazonec2_ami:                    "ami-221ea342"
        amazonec2_block_duration_minutes: "0"
        amazonec2_device_name:            "/dev/xvda"
        amazonec2_instance_type:          "t2.nano"
        amazonec2_keypair_name:           "docker-machine"
        amazonec2_region:                 "us-west-2"
        amazonec2_retries:                "5"
        amazonec2_root_size:              "8"
        amazonec2_security_group.#:       "1"
        amazonec2_security_group.0:       "docker-machine"
        amazonec2_spot_price:             "0.50"
        amazonec2_ssh_user:               "admin"
        amazonec2_volume_type:            "gp2"
        amazonec2_zone:                   "a"
        certs_directory:                  <computed>
        docker_url:                       <computed>
        docker_version:                   <computed>
        engine_insecure_registry.#:       "3"
        engine_insecure_registry.0:       "localhost:5000"
        engine_insecure_registry.1:       "registry:5000"
        engine_insecure_registry.2:       "127.0.0.1:5000"
        name:                             "node-01"
        ssh_hostname:                     <computed>
        ssh_keypath:                      <computed>
        ssh_port:                         <computed>
        ssh_username:                     <computed>
        state:                            "running"
        storage_path_computed:            <computed>
        swarm:                            "false"
        swarm_experimental:               "false"
        swarm_master:                     "false"
        tls_server_cert:                  <computed>
        tls_server_key:                   <computed>


  Plan: 1 to add, 0 to change, 0 to destroy.

  Do you want to perform these actions?
    Terraform will perform the actions described above.
    Only 'yes' will be accepted to approve.

    Enter a value: yes

  2018/03/16 15:27:21 [INFO] terraform: building graph: GraphTypeApply
  > "<computed>"
    swarm:                            "" => "false" (forces new resource)
    swarm_experimental:               "" => "false" (forces new resource)
    swarm_master:                     "" => "false" (forces new resource)
    tls_server_cert:                  "" => "<computed>"
    tls_server_key:                   "" => "<computed>"
  rDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "amazonec2_security_group.0":*terraform.ResourceAttrDiff{Old:"", New:"docker-machine", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "amazonec2_device_name":*terraform.ResourceAttrDiff{Old:"", New:"/dev/xvda", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "swarm":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "amazonec2_root_size":*terraform.ResourceAttrDiff{Old:"", New:"8", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "docker_version":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "amazonec2_volume_type":*terraform.ResourceAttrDiff{Old:"", New:"gp2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "storage_path_computed":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "amazonec2_ssh_user":*terraform.ResourceAttrDiff{Old:"", New:"admin", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "ssh_port":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "engine_insecure_registry.0":*terraform.ResourceAttrDiff{Old:"", New:"localhost:5000", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x2}, "amazonec2_block_duration_minutes":*terraform.ResourceAttrDiff{Old:"", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "certs_directory":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "ssh_hostname":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "amazonec2_keypair_name":*terraform.ResourceAttrDiff{Old:"", New:"docker-machine", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "amazonec2_region":*terraform.ResourceAttrDiff{Old:"", New:"us-west-2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "ssh_username":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "address":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "swarm_master":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "amazonec2_instance_type":*terraform.ResourceAttrDiff{Old:"", New:"t2.nano", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "docker_url":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"node-01", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "amazonec2_spot_price":*terraform.ResourceAttrDiff{Old:"", New:"0.50", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "amazonec2_retries":*terraform.ResourceAttrDiff{Old:"", New:"5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
  ences: []
  2018/03/16 15:27:21 [DEBUG] ReferenceTransformer: "output.public_ip" references: []
  2018/03/16 15:27:21 [DEBUG] ReferenceTransformer: "output.private_ip" references: []
  2018/03/16 15:27:21 [TRACE] Graph after step *terraform.ReferenceTransformer:

  dockermachine_amazonec2.node - *terraform.NodeApplyableResource
    provider.dockermachine - *terraform.NodeApplyableProvider
    provisioner.remote-exec - *terraform.NodeProvisioner
  output.private_ip - *terraform.NodeApplyableOutput
  output.public_ip - *terraform.NodeApplyableOutput
  provider.dockermachine - *terraform.NodeApplyableProvider
  provisioner.remote-exec - *terraform.NodeProvisioner
  2018/03/16 15:27:21 [TRACE] Graph after step *terraform.CountBoundaryTransformer:

  dockermachine_amazonec2.node - *terraform.NodeApplyableResource
    provider.dockermachine - *terraform.NodeApplyableProvider
    provisioner.remote-exec - *terraform.NodeProvisioner
  meta.count-boundary (count boundary fixup) - *terraform.NodeCountBoundary
    dockermachine_amazonec2.node - *terraform.NodeApplyableResource
    output.private_ip - *terraform.NodeApplyableOutput
    output.public_ip - *terraform.NodeApplyableOutput
    provider.dockermachine - *terraform.NodeApplyableProvider
    provisioner.remote-exec - *terraform.NodeProvisioner
  output.private_ip - *terraform.NodeApplyableOutput
  output.public_ip - *terraform.NodeApplyableOutput
  provider.dockermachine - *terraform.NodeApplyableProvider
  provisioner.remote-exec - *terraform.NodeProvisioner
  2018/03/16 15:27:21 [TRACE] Graph after step *terraform.TargetsTransformer:

  dockermachine_amazonec2.node - *terraform.NodeApplyableResource
    provider.dockermachine - *terraform.NodeApplyableProvider
    provisioner.remote-exec - *terraform.NodeProvisioner
  meta.count-boundary (count boundary fixup) - *terraform.NodeCountBoundary
    dockermachine_amazonec2.node - *terraform.NodeApplyableResource
    output.private_ip - *terraform.NodeApplyableOutput
    output.public_ip - *terraform.NodeApplyableOutput
    provider.dockermachine - *terraform.NodeApplyableProvider
    prdockermachine_amazonec2.node: Creating...
    address:                          "" => "<computed>"
    amazonec2_ami:                    "" => "ami-221ea342"
    amazonec2_block_duration_minutes: "" => "0"
    amazonec2_device_name:            "" => "/dev/xvda"
    amazonec2_instance_type:          "" => "t2.nano"
    amazonec2_keypair_name:           "" => "docker-machine"
    amazonec2_region:                 "" => "us-west-2"
    amazonec2_retries:                "" => "5"
    amazonec2_root_size:              "" => "8"
    amazonec2_security_group.#:       "" => "1"
    amazonec2_security_group.0:       "" => "docker-machine"
    amazonec2_spot_price:             "" => "0.50"
    amazonec2_ssh_user:               "" => "admin"
    amazonec2_volume_type:            "" => "gp2"
    amazonec2_zone:                   "" => "a"
    certs_directory:                  "" => "<computed>"
    docker_url:                       "" => "<computed>"
    docker_version:                   "" => "<computed>"
    engine_insecure_registry.#:       "" => "3"
    engine_insecure_registry.0:       "" => "localhost:5000"
    engine_insecure_registry.1:       "" => "registry:5000"
    engine_insecure_registry.2:       "" => "127.0.0.1:5000"
    name:                             "" => "node-01"
    ssh_hostname:                     "" => "<computed>"
    ssh_keypath:                      "" => "<computed>"
    ssh_port:                         "" => "<computed>"
    ssh_username:                     "" => "<computed>"
    state:                            "" => "running"
    storage_path_computed:            "" => "<computed>"
    swarm:                            "" => "false"
    swarm_experimental:               "" => "false"
    swarm_master:                     "" => "false"
    tls_server_cert:                  "" => "<computed>"
    tls_server_key:                   "" => "<computed>"

  Error: Error applying plan:

  1 error(s) occurred:

  * dockermachine_amazonec2.node: 1 error(s) occurred:

  * dockermachine_amazonec2.node: unexpected EOF

  Terraform does not automatically rollback in the face of errors.
  Instead, your Terraform state file has been partially updated with
  any resources that successfully completed. Please address the error
  above and apply again to incrementally change your infrastructure.


  panic: interface conversion: interface {} is []interface {}, not []string
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: 
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: goroutine 46 [running]:
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: github.com/gstruct/terraform-provider-dockermachine/provider.getDriverOpts(0xc42014a5b0, 0xc42060cd20, 0x1e, 0x1e, 0xc4202528c0, 0x20)
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/Users/wbr/go/src/github.com/gstruct/terraform-provider-dockermachine/provider/resource.go:330 +0x87a
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: github.com/gstruct/terraform-provider-dockermachine/provider.resourceCreate.func1(0xc42014a5b0, 0x245e8c0, 0xc4203f64b0, 0xc42014a5b0, 0x0)
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/Users/wbr/go/src/github.com/gstruct/terraform-provider-dockermachine/provider/resource_create.go:97 +0x15db
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4201268c0, 0xc42023c2d0, 0xc42010dc20, 0x245e8c0, 0xc4203f64b0, 0xc42022c801, 0xc420573b88, 0x10b772c)
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/Users/wbr/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:227 +0x35a
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc420127030, 0xc42023c230, 0xc42023c2d0, 0xc42010dc20, 0x18, 0x18, 0xc42010dc60)
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/Users/wbr/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa4
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc42022ebe0, 0xc42010d180, 0xc42042e390, 0x0, 0x0)
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/Users/wbr/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: reflect.Value.call(0xc42025c840, 0xc42040e320, 0x13, 0x2538551, 0x4, 0xc420573f18, 0x3, 0x3, 0xc420229500, 0x0, ...)
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:447 +0x969
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: reflect.Value.Call(0xc42025c840, 0xc42040e320, 0x13, 0xc4203ff718, 0x3, 0x3, 0x0, 0x0, 0x300000007)
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:308 +0xa4
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: net/rpc.(*service).call(0xc4204acec0, 0xc4203f63c0, 0xc4204e8450, 0xc4204e8460, 0xc42044e000, 0xc4204ed0e0, 0x208f340, 0xc42010d180, 0x16, 0x208f380, ...)
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/usr/local/Cellar/go/1.10/libexec/src/net/rpc/server.go:384 +0x14e
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: created by net/rpc.(*Server).ServeCodec
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/usr/local/Cellar/go/1.10/libexec/src/net/rpc/server.go:480 +0x43a
  2018/03/16 15:27:21 [TRACE] root: eval: *terraform.EvalWriteState
  2018/03/16 15:27:21 [TRACE] root: eval: *terraform.EvalApplyProvisioners
  2018/03/16 15:27:21 [TRACE] root: eval: *terraform.EvalIf
  2018/03/16 15:27:21 [TRACE] root: eval: *terraform.EvalWriteState
  2018/03/16 15:27:21 [TRACE] root: eval: *terraform.EvalWriteDiff
  2018/03/16 15:27:21 [TRACE] root: eval: *terraform.EvalApplyPost
  2018/03/16 15:27:21 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

  * dockermachine_amazonec2.node: unexpected EOF
  2018/03/16 15:27:21 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

  * dockermachine_amazonec2.node: unexpected EOF
  2018/03/16 15:27:21 [TRACE] [walkApply] Exiting eval tree: dockermachine_amazonec2.node
  2018/03/16 15:27:21 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
  2018/03/16 15:27:21 [TRACE] dag/walk: upstream errored, not walking "provisioner.remote-exec (close)"
  2018/03/16 15:27:21 [TRACE] dag/walk: upstream errored, not walking "provider.dockermachine (close)"
  2018/03/16 15:27:21 [TRACE] dag/walk: upstream errored, not walking "root"
  2018-03-16T15:27:21.634-0700 [DEBUG] plugin: plugin process exited: path=/Users/wbr/Documents/Programming/GitProjects/Docker/terraform/.terraform/plugins/darwin_amd64/terraform-provider-dockermachine
  2018/03/16 15:27:21 [TRACE] Preserving existing state lineage "d85f942d-75a5-43c8-a0ab-cec40de847fe"
  2018/03/16 15:27:21 [TRACE] Preserving existing state lineage "d85f942d-75a5-43c8-a0ab-cec40de847fe"
  2018/03/16 15:27:21 [TRACE] Preserving existing state lineage "d85f942d-75a5-43c8-a0ab-cec40de847fe"
  2018/03/16 15:27:21 [TRACE] Preserving existing state lineage "d85f942d-75a5-43c8-a0ab-cec40de847fe"
  2018/03/16 15:27:21 [DEBUG] plugin: waiting for all plugin processes to complete...
  2018-03-16T15:27:21.638-0700 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
  2018-03-16T15:27:21.640-0700 [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2018/03/16 15:27:21 [DEBUG] plugin: waiting for all plugin processes to complete...
  2018-03-16T15:27:21.642-0700 [DEBUG] plugin.terraform: file-provisioner (internal) 2018/03/16 15:27:21 [DEBUG] plugin: waiting for all plugin processes to complete...
  2018-03-16T15:27:21.644-0700 [DEBUG] plugin: plugin process exited: path=/usr/local/Cellar/terraform/0.11.3/bin/terraform
  2018-03-16T15:27:21.644-0700 [DEBUG] plugin: plugin process exited: path=/Users/wbr/Documents/Programming/GitProjects/Docker/terraform/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.11.0_x4
  2018-03-16T15:27:21.644-0700 [DEBUG] plugin: plugin process exited: path=/usr/local/Cellar/terraform/0.11.3/bin/terraform
  panic: interface conversion: interface {} is []interface {}, not []string
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: 
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: goroutine 46 [running]:
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: github.com/gstruct/terraform-provider-dockermachine/provider.getDriverOpts(0xc42014a5b0, 0xc42060cd20, 0x1e, 0x1e, 0xc4202528c0, 0x20)
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/Users/wbr/go/src/github.com/gstruct/terraform-provider-dockermachine/provider/resource.go:330 +0x87a
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: github.com/gstruct/terraform-provider-dockermachine/provider.resourceCreate.func1(0xc42014a5b0, 0x245e8c0, 0xc4203f64b0, 0xc42014a5b0, 0x0)
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/Users/wbr/go/src/github.com/gstruct/terraform-provider-dockermachine/provider/resource_create.go:97 +0x15db
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4201268c0, 0xc42023c2d0, 0xc42010dc20, 0x245e8c0, 0xc4203f64b0, 0xc42022c801, 0xc420573b88, 0x10b772c)
  2018-03-16T15:27:21.629-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/Users/wbr/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:227 +0x35a
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc420127030, 0xc42023c230, 0xc42023c2d0, 0xc42010dc20, 0x18, 0x18, 0xc42010dc60)
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/Users/wbr/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa4
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc42022ebe0, 0xc42010d180, 0xc42042e390, 0x0, 0x0)
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/Users/wbr/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: reflect.Value.call(0xc42025c840, 0xc42040e320, 0x13, 0x2538551, 0x4, 0xc420573f18, 0x3, 0x3, 0xc420229500, 0x0, ...)
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:447 +0x969
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: reflect.Value.Call(0xc42025c840, 0xc42040e320, 0x13, 0xc4203ff718, 0x3, 0x3, 0x0, 0x0, 0x300000007)
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:308 +0xa4
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: net/rpc.(*service).call(0xc4204acec0, 0xc4203f63c0, 0xc4204e8450, 0xc4204e8460, 0xc42044e000, 0xc4204ed0e0, 0x208f340, 0xc42010d180, 0x16, 0x208f380, ...)
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/usr/local/Cellar/go/1.10/libexec/src/net/rpc/server.go:384 +0x14e
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: created by net/rpc.(*Server).ServeCodec
  2018-03-16T15:27:21.630-0700 [DEBUG] plugin.terraform-provider-dockermachine: 	/usr/local/Cellar/go/1.10/libexec/src/net/rpc/server.go:480 +0x43a
  2018/03/16 15:27:21 [TRACE] root: eval: *terraform.EvalWriteState
  2018/03/16 15:27:21 [TRACE] root: eval: *terraform.EvalApplyProvisioners
  2018/03/16 15:27:21 [TRACE] root: eval: *terraform.EvalIf
  2018/03/16 15:27:21 [TRACE] root: eval: *terraform.EvalWriteState
  2018/03/16 15:27:21 [TRACE] root: eval: *terraform.EvalWriteDiff
  2018/03/16 15:27:21 [TRACE] root: eval: *terraform.EvalApplyPost
  2018/03/16 15:27:21 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

  * dockermachine_amazonec2.node: unexpected EOF
  2018/03/16 15:27:21 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

  * dockermachine_amazonec2.node: unexpected EOF
  2018/03/16 15:27:21 [TRACE] [walkApply] Exiting eval tree: dockermachine_amazonec2.node
  2018/03/16 15:27:21 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
  2018/03/16 15:27:21 [TRACE] dag/walk: upstream errored, not walking "provisioner.remote-exec (close)"
  2018/03/16 15:27:21 [TRACE] dag/walk: upstream errored, not walking "provider.dockermachine (close)"
  2018/03/16 15:27:21 [TRACE] dag/walk: upstream errored, not walking "root"
  2018-03-16T15:27:21.634-0700 [DEBUG] plugin: plugin process exited: path=/Users/wbr/Documents/Programming/GitProjects/Docker/terraform/.terraform/plugins/darwin_amd64/terraform-provider-dockermachine
  2018/03/16 15:27:21 [TRACE] Preserving existing state lineage "d85f942d-75a5-43c8-a0ab-cec40de847fe"
  2018/03/16 15:27:21 [TRACE] Preserving existing state lineage "d85f942d-75a5-43c8-a0ab-cec40de847fe"
  2018/03/16 15:27:21 [TRACE] Preserving existing state lineage "d85f942d-75a5-43c8-a0ab-cec40de847fe"
  2018/03/16 15:27:21 [TRACE] Preserving existing state lineage "d85f942d-75a5-43c8-a0ab-cec40de847fe"
  2018/03/16 15:27:21 [DEBUG] plugin: waiting for all plugin processes to complete...
  2018-03-16T15:27:21.638-0700 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
  2018-03-16T15:27:21.640-0700 [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2018/03/16 15:27:21 [DEBUG] plugin: waiting for all plugin processes to complete...
  2018-03-16T15:27:21.642-0700 [DEBUG] plugin.terraform: file-provisioner (internal) 2018/03/16 15:27:21 [DEBUG] plugin: waiting for all plugin processes to complete...
  2018-03-16T15:27:21.644-0700 [DEBUG] plugin: plugin process exited: path=/usr/local/Cellar/terraform/0.11.3/bin/terraform
  2018-03-16T15:27:21.644-0700 [DEBUG] plugin: plugin process exited: path=/Users/wbr/Documents/Programming/GitProjects/Docker/terraform/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.11.0_x4
  2018-03-16T15:27:21.644-0700 [DEBUG] plugin: plugin process exited: path=/usr/local/Cellar/terraform/0.11.3/bin/terraform



  !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

  Terraform crashed! This is always indicative of a bug within Terraform.
  A crash log has been placed at "crash.log" relative to your current
  working directory. It would be immensely helpful if you could please
  report the crash with Terraform[1] so that we can fix this.

  When reporting bugs, please include your terraform version. That
  information is available on the first line of crash.log. You can also
  get it by running 'terraform --version' on the command line.

  [1]: https://github.com/hashicorp/terraform/issues

  !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
  registry:terraform wbr$ 
```

**Comment by giacomocariello** [comment]
Hi, Thanks for posting. Release 0.1.3 should fix the bug. Could you please check if it solves your problem?

**Comment by giacomocariello** [comment]
The problem seems fixed. Please reopen the issue if your feedback is negative.

**Comment by ginjo** [comment]
Thanks for the help @giacomocariello , I'll give it another try.
